require 'user.options'
require 'user.keymaps'
require 'user.coc_keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.indent_o_matic'
require 'user.treesitter'
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
